### DISCUSSION TITLE
Change default user in Docker?

### DISCUSSION THREAD

**Discussion by Hazmi35** [cloudamqp/lavinmq#593] [General]
Is there a way to change the default user in Docker like in RabbitMQ using environment variables?

Like:
```env
RABBITMQ_DEFAULT_USER=tune
RABBITMQ_DEFAULT_PASS=BFcBsUB5AZHBnEMibkEspFvJF3nAu6KNBUfxgv9MySBZSp3CA2UgNLkRjhRDcQ8p
```

**Comment by carlhoerberg** [comment]
Yes, with the --user argument to Docker run
https://docs.docker.com/engine/reference/run/#user

**Reply by Hazmi35** [reply]
I'm sorry I think you missunderstood the question

I'm looking to change the LavinMQ user, not the running user inside the Docker container.

**Comment by carlhoerberg** [comment]
Oh, I see. Normally you would like to do a lot more than just change the
user, such as adding vhosts, adding policies. I would recommend
prepopulating the data directory, eg. the users.json file for the default
users.

**Comment by danielwertheim** [comment]
Was looking for something similar for evaluation purposes where I'm replacing an existing rabbitmq compose file and used the solution below. Not sure if it's applicable to your case (and perhaps you have moved on as it's rather old). Otherwise maybe for someone else.

```yaml
services:
  lavinmq:
    image: cloudamqp/lavinmq:latest
    restart: unless-stopped
    configs:
      - source: lavinmq_config
        target: /etc/lavinmq/lavinmq.ini
    ports:
      - 15672:15672 # HTTP
      - 5672:5672 # AMQP
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
        compress: "false"

configs:
  lavinmq_config:
    content: |
        [main]
        default_user = someuser
        default_password = somehashedpassword
```

The password can be generated e.g. using `lavinmqctl hash_password somepassword`
